apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubesnooper
  name: kubesnooper
spec:
  ports:
  - name: kubesnooper
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: kubesnooper
  type: LoadBalancer
