apiVersion: v1
kind: Service
metadata:
 labels:
   app: kubesnooper
 name: kubesnooper
spec:
 ports:
   port: 80
   protocol: TCP
   targetPort: 4000
 selector:
   app: kubesnooper
 type: LoadBalancer